<?php

// Complete dictionary of essential universities across Indonesia
// including Muhammadiyah, Nahdlatul Ulama, PTN, UIN, and top PTS
$curatedAdditions = [
    // --- SIDOARJO & SEKITARNYA ---
    'universitas muhammadiyah sidoarjo' => [
        'kode' => '071060',
        'singkat' => 'UMSIDA',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Sidoarjo',
        'lat' => -7.467017,
        'lng' => 112.716830,
        'web' => 'https://umsida.ac.id',
        'alamat' => 'Jl. Majapahit No. 666 B, Celep, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61215',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas nahdlatul ulama sidoarjo' => [
        'kode' => '071092',
        'singkat' => 'UNUSIDA',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Sidoarjo',
        'lat' => -7.452300,
        'lng' => 112.718900,
        'web' => 'https://unusida.ac.id',
        'alamat' => 'Jl. Lingkar Timur Km. 5, Rangkah Kidul, Sidoarjo, Jawa Timur 61234',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas maarif hasyim latif' => [
        'kode' => '071091',
        'singkat' => 'UMAHA',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Sidoarjo',
        'lat' => -7.412300,
        'lng' => 112.678900,
        'web' => 'https://umaha.ac.id',
        'alamat' => 'Jl. Ngelom Megare No. 30, Ngelom, Taman, Sidoarjo, Jawa Timur 61257',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],

    // --- SURABAYA & JAWA TIMUR PTS / KAMPUS POPULER ---
    'universitas muhammadiyah surabaya' => [
        'kode' => '071034',
        'singkat' => 'UMSurabaya',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.271100,
        'lng' => 112.795600,
        'web' => 'https://um-surabaya.ac.id',
        'alamat' => 'Jl. Sutorejo No. 59, Dukuh Sutorejo, Mulyorejo, Surabaya, Jawa Timur 60113',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas nahdlatul ulama surabaya' => [
        'kode' => '071088',
        'singkat' => 'UNUSA',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.314500,
        'lng' => 112.735600,
        'web' => 'https://unusa.ac.id',
        'alamat' => 'Jl. Jemursari No. 51-57, Jemur Wonosari, Wonocolo, Surabaya, Jawa Timur 60237',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas pembangunan nasional veteran jawa timur' => [
        'kode' => '001043',
        'singkat' => 'UPN Jatim',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.333300,
        'lng' => 112.788900,
        'web' => 'https://upnjatim.ac.id',
        'alamat' => 'Jl. Rungkut Madya No. 1, Gunung Anyar, Surabaya, Jawa Timur 60294',
        'jenis' => 'universitas',
        'kelompok' => 'PTN',
    ],
    'universitas surabaya' => [
        'kode' => '071018',
        'singkat' => 'UBAYA',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.321100,
        'lng' => 112.768900,
        'web' => 'https://ubaya.ac.id',
        'alamat' => 'Jl. Raya Kalirungkut, Rungkut, Surabaya, Jawa Timur 60293',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas katolik widya mandala surabaya' => [
        'kode' => '071003',
        'singkat' => 'UKWMS',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.288900,
        'lng' => 112.748900,
        'web' => 'https://ukwms.ac.id',
        'alamat' => 'Jl. Dinoyo No. 42-44, Keputran, Tegalsari, Surabaya, Jawa Timur 60265',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas 17 agustus 1945 surabaya' => [
        'kode' => '071010',
        'singkat' => 'UNTAG Surabaya',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.298900,
        'lng' => 112.767800,
        'web' => 'https://untag-sby.ac.id',
        'alamat' => 'Jl. Semolowaru No. 45, Menur Pumpungan, Sukolilo, Surabaya, Jawa Timur 60118',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas 17 agustus 1945 jakarta' => [
        'kode' => '031014',
        'singkat' => 'UNTAG Jakarta',
        'akred' => 'Baik Sekali',
        'prov' => 'DKI Jakarta',
        'kab' => 'Kota Jakarta Utara',
        'lat' => -6.138900,
        'lng' => 106.878900,
        'web' => 'https://uta45jakarta.ac.id',
        'alamat' => 'Jl. Sunter Permai Raya, Sunter Agung, Tanjung Priok, Jakarta Utara, DKI Jakarta 14350',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas 17 agustus 1945 semarang' => [
        'kode' => '061003',
        'singkat' => 'UNTAG Semarang',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kota Semarang',
        'lat' => -7.012300,
        'lng' => 110.398900,
        'web' => 'https://untagsmg.ac.id',
        'alamat' => 'Jl. Pawiyatan Luhur, Bendan Dhuwur, Gajahmungkur, Kota Semarang, Jawa Tengah 50233',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas 17 agustus 1945 cirebon' => [
        'kode' => '041010',
        'singkat' => 'UNTAG Cirebon',
        'akred' => 'Unggul',
        'prov' => 'Jawa Barat',
        'kab' => 'Kota Cirebon',
        'lat' => -6.745600,
        'lng' => 108.535600,
        'web' => 'https://untagcirebon.ac.id',
        'alamat' => 'Jl. Perjuangan No. 17, Karyamulya, Kesambi, Kota Cirebon, Jawa Barat 45131',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas 17 agustus 1945 banyuwangi' => [
        'kode' => '071064',
        'singkat' => 'UNTAG Banyuwangi',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Banyuwangi',
        'lat' => -8.235600,
        'lng' => 114.365600,
        'web' => 'https://untag-bwx.ac.id',
        'alamat' => 'Jl. Adi Sucipto No. 26, Sobo, Kec. Banyuwangi, Kabupaten Banyuwangi, Jawa Timur 68418',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas 17 agustus 1945 samarinda' => [
        'kode' => '111005',
        'singkat' => 'UNTAG Samarinda',
        'akred' => 'Baik Sekali',
        'prov' => 'Kalimantan Timur',
        'kab' => 'Kota Samarinda',
        'lat' => -0.485600,
        'lng' => 117.135600,
        'web' => 'https://untag-smd.ac.id',
        'alamat' => 'Jl. Ir. H. Juanda No. 80, Air Hitam, Kec. Samarinda Ulu, Kota Samarinda, Kalimantan Timur 75124',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas dr soetomo' => [
        'kode' => '071035',
        'singkat' => 'UNITOMO',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.295600,
        'lng' => 112.767800,
        'web' => 'https://unitomo.ac.id',
        'alamat' => 'Jl. Semolowaru No. 84, Menur Pumpungan, Sukolilo, Surabaya, Jawa Timur 60118',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas bhayangkara surabaya' => [
        'kode' => '071033',
        'singkat' => 'UBHARA Surabaya',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.317800,
        'lng' => 112.730100,
        'web' => 'https://ubhara.ac.id',
        'alamat' => 'Jl. Ahmad Yani No. 114, Ketintang, Gayungan, Surabaya, Jawa Timur 60231',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas wijaya kusuma surabaya' => [
        'kode' => '071026',
        'singkat' => 'UWKS',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.275600,
        'lng' => 112.708900,
        'web' => 'https://uwks.ac.id',
        'alamat' => 'Jl. Dukuh Kupang XXV No. 54, Dukuh Kupang, Dukuhpakis, Surabaya, Jawa Timur 60225',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas hang tuah' => [
        'kode' => '071043',
        'singkat' => 'UHT',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.288900,
        'lng' => 112.795600,
        'web' => 'https://hangtuah.ac.id',
        'alamat' => 'Jl. Arief Rahman Hakim No. 150, Keputih, Sukolilo, Surabaya, Jawa Timur 60111',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas narotama' => [
        'kode' => '071030',
        'singkat' => 'UNNAR',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.291200,
        'lng' => 112.775600,
        'web' => 'https://narotama.ac.id',
        'alamat' => 'Jl. Arief Rahman Hakim No. 51, Sukolilo, Surabaya, Jawa Timur 60117',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas pgri adi buana surabaya' => [
        'kode' => '071037',
        'singkat' => 'UNIPA Surabaya',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.318900,
        'lng' => 112.768900,
        'web' => 'https://unipasby.ac.id',
        'alamat' => 'Jl. Dukuh Menanggal XII, Dukuh Menanggal, Gayungan, Surabaya, Jawa Timur 60234',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas dinamika' => [
        'kode' => '071095',
        'singkat' => 'UNDIKA / STIKOM',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.312300,
        'lng' => 112.775600,
        'web' => 'https://dinamika.ac.id',
        'alamat' => 'Jl. Raya Kedung Baruk No. 98, Rungkut, Surabaya, Jawa Timur 60298',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah gresik' => [
        'kode' => '071029',
        'singkat' => 'UMG',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Gresik',
        'lat' => -7.164500,
        'lng' => 112.635600,
        'web' => 'https://umg.ac.id',
        'alamat' => 'Jl. Sumatera No. 101, Randuagung, Kebomas, Gresik, Jawa Timur 61121',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah jember' => [
        'kode' => '071019',
        'singkat' => 'UM Jember',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Jember',
        'lat' => -8.167800,
        'lng' => 113.725600,
        'web' => 'https://unmuhjember.ac.id',
        'alamat' => 'Jl. Karimata No. 49, Sumbersari, Jember, Jawa Timur 68121',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah ponorogo' => [
        'kode' => '071017',
        'singkat' => 'UMPO',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Ponorogo',
        'lat' => -7.868900,
        'lng' => 111.475600,
        'web' => 'https://umpo.ac.id',
        'alamat' => 'Jl. Budi Utomo No. 10, Ronowijayan, Siman, Ponorogo, Jawa Timur 63471',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah lamongan' => [
        'kode' => '071099',
        'singkat' => 'UMLA',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Lamongan',
        'lat' => -7.123400,
        'lng' => 112.425600,
        'web' => 'https://umla.ac.id',
        'alamat' => 'Jl. Raya Plalangan Plosowahyu Km. 02, Lamongan, Jawa Timur 62218',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah madiun' => [
        'kode' => '071108',
        'singkat' => 'UMMAD',
        'akred' => 'Baik',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Madiun',
        'lat' => -7.632100,
        'lng' => 111.535600,
        'web' => 'https://ummad.ac.id',
        'alamat' => 'Jl. Mayjen Panjaitan No. 18, Banjarejo, Taman, Kota Madiun, Jawa Timur 63137',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas islam lamongan' => [
        'kode' => '071061',
        'singkat' => 'UNISLA',
        'akred' => 'Baik Sekali',
        'prov' => 'Jawa Timur',
        'kab' => 'Kabupaten Lamongan',
        'lat' => -7.125600,
        'lng' => 112.415600,
        'web' => 'https://unisla.ac.id',
        'alamat' => 'Jl. Veteran No. 53A, Lamongan, Jawa Timur 62211',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],

    // --- UIN / IAIN SELURUH INDONESIA ---
    'uin sunan ampel surabaya' => [
        'kode' => '201004',
        'singkat' => 'UINSA',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Surabaya',
        'lat' => -7.317500,
        'lng' => 112.736900,
        'web' => 'https://uinsby.ac.id',
        'alamat' => 'Jl. Ahmad Yani No. 117, Jemur Wonosari, Wonocolo, Surabaya, Jawa Timur 60237',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin maulana malik ibrahim malang' => [
        'kode' => '201005',
        'singkat' => 'UIN Malang',
        'akred' => 'Unggul',
        'prov' => 'Jawa Timur',
        'kab' => 'Kota Malang',
        'lat' => -7.952200,
        'lng' => 112.607800,
        'web' => 'https://uin-malang.ac.id',
        'alamat' => 'Jl. Gajayana No. 50, Dinoyo, Lowokwaru, Malang, Jawa Timur 65144',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin sunan kalijaga yogyakarta' => [
        'kode' => '201002',
        'singkat' => 'UIN Suka',
        'akred' => 'Unggul',
        'prov' => 'DI Yogyakarta',
        'kab' => 'Kabupaten Sleman',
        'lat' => -7.784500,
        'lng' => 110.395600,
        'web' => 'https://uin-suka.ac.id',
        'alamat' => 'Jl. Marsda Adisucipto No. 1, Caturtunggal, Depok, Sleman, DIY 55281',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin syarif hidayatullah jakarta' => [
        'kode' => '201001',
        'singkat' => 'UIN Jakarta',
        'akred' => 'Unggul',
        'prov' => 'Banten',
        'kab' => 'Kota Tangerang Selatan',
        'lat' => -6.305600,
        'lng' => 106.755600,
        'web' => 'https://uinjkt.ac.id',
        'alamat' => 'Jl. Ir. H. Juanda No. 95, Cempaka Putih, Ciputat Timur, Tangerang Selatan 15412',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin walisongo semarang' => [
        'kode' => '201003',
        'singkat' => 'UIN Walisongo',
        'akred' => 'Unggul',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kota Semarang',
        'lat' => -6.991200,
        'lng' => 110.345600,
        'web' => 'https://walisongo.ac.id',
        'alamat' => 'Jl. Prof. Hamka, Tambakaji, Ngaliyan, Semarang, Jawa Tengah 50185',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin alauddin makassar' => [
        'kode' => '201006',
        'singkat' => 'UIN Alauddin',
        'akred' => 'Unggul',
        'prov' => 'Sulawesi Selatan',
        'kab' => 'Kabupaten Gowa',
        'lat' => -5.204500,
        'lng' => 119.495600,
        'web' => 'https://uin-alauddin.ac.id',
        'alamat' => 'Jl. H. M. Yasin Limpo No. 36, Romangpolong, Somba Opu, Gowa, Sulawesi Selatan 92118',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin ar-raniry banda aceh' => [
        'kode' => '201008',
        'singkat' => 'UIN Ar-Raniry',
        'akred' => 'Unggul',
        'prov' => 'Aceh',
        'kab' => 'Kota Banda Aceh',
        'lat' => 5.567800,
        'lng' => 95.368900,
        'web' => 'https://ar-raniry.ac.id',
        'alamat' => 'Jl. Lingkar Kampus, Kopelma Darussalam, Syiah Kuala, Banda Aceh 23111',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin sumatera utara medan' => [
        'kode' => '201007',
        'singkat' => 'UINSU',
        'akred' => 'Unggul',
        'prov' => 'Sumatera Utara',
        'kab' => 'Kota Medan',
        'lat' => 3.605600,
        'lng' => 98.715600,
        'web' => 'https://uinsu.ac.id',
        'alamat' => 'Jl. Willem Iskandar Pasar V, Medan Estate, Percut Sei Tuan, Deli Serdang 20371',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin raden fatah palembang' => [
        'kode' => '201009',
        'singkat' => 'UIN Palembang',
        'akred' => 'Unggul',
        'prov' => 'Sumatera Selatan',
        'kab' => 'Kota Palembang',
        'lat' => -2.965600,
        'lng' => 104.755600,
        'web' => 'https://radenfatah.ac.id',
        'alamat' => 'Jl. Prof. K. H. Zainal Abidin Fikri No. 1, Palembang, Sumatera Selatan 30126',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin imam bonjol padang' => [
        'kode' => '201010',
        'singkat' => 'UIN Padang',
        'akred' => 'Unggul',
        'prov' => 'Sumatera Barat',
        'kab' => 'Kota Padang',
        'lat' => -0.875600,
        'lng' => 100.375600,
        'web' => 'https://uinib.ac.id',
        'alamat' => 'Jl. Prof. Mahmud Yunus No. 1, Lubuk Lintah, Kuranji, Padang, Sumatera Barat 25153',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],
    'uin antasari banjarmasin' => [
        'kode' => '201014',
        'singkat' => 'UIN Antasari',
        'akred' => 'Unggul',
        'prov' => 'Kalimantan Selatan',
        'kab' => 'Kota Banjarmasin',
        'lat' => -3.324500,
        'lng' => 114.615600,
        'web' => 'https://uin-antasari.ac.id',
        'alamat' => 'Jl. Jenderal Ahmad Yani Km. 4.5, Banjarmasin, Kalimantan Selatan 70235',
        'jenis' => 'universitas',
        'kelompok' => 'PTA',
    ],

    // --- MUHAMMADIYAH NASIONAL POPULER ---
    'universitas ahmad dahlan' => [
        'kode' => '051015',
        'singkat' => 'UAD',
        'akred' => 'Unggul',
        'prov' => 'DI Yogyakarta',
        'kab' => 'Kota Yogyakarta',
        'lat' => -7.828900,
        'lng' => 110.385600,
        'web' => 'https://uad.ac.id',
        'alamat' => 'Jl. Kapas No. 9, Semaki, Umbulharjo, Kota Yogyakarta, DIY 55166',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah purwokerto' => [
        'kode' => '061026',
        'singkat' => 'UMP',
        'akred' => 'Unggul',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kabupaten Banyumas',
        'lat' => -7.415600,
        'lng' => 109.265600,
        'web' => 'https://ump.ac.id',
        'alamat' => 'Jl. KH. Ahmad Dahlan, Dukuhwaluh, Kembaran, Banyumas, Jawa Tengah 53182',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah semarang' => [
        'kode' => '061036',
        'singkat' => 'UNIMUS',
        'akred' => 'Unggul',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kota Semarang',
        'lat' => -7.025600,
        'lng' => 110.455600,
        'web' => 'https://unimus.ac.id',
        'alamat' => 'Jl. Kedungmundu Raya No. 18, Tembalang, Semarang, Jawa Tengah 50273',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah magelang' => [
        'kode' => '061019',
        'singkat' => 'UNIMMA',
        'akred' => 'Unggul',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kabupaten Magelang',
        'lat' => -7.535600,
        'lng' => 110.235600,
        'web' => 'https://unimma.ac.id',
        'alamat' => 'Jl. Mayjen Bambang Soegeng Km. 5, Mertoyudan, Magelang, Jawa Tengah 56172',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah prof dr hamka' => [
        'kode' => '031008',
        'singkat' => 'UHAMKA',
        'akred' => 'Unggul',
        'prov' => 'DKI Jakarta',
        'kab' => 'Kota Jakarta Selatan',
        'lat' => -6.241200,
        'lng' => 106.795600,
        'web' => 'https://uhamka.ac.id',
        'alamat' => 'Jl. Limau II, Kebayoran Baru, Jakarta Selatan 12130',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah jakarta' => [
        'kode' => '031001',
        'singkat' => 'UMJ',
        'akred' => 'Unggul',
        'prov' => 'Banten',
        'kab' => 'Kota Tangerang Selatan',
        'lat' => -6.308900,
        'lng' => 106.765600,
        'web' => 'https://umj.ac.id',
        'alamat' => 'Jl. KH. Ahmad Dahlan, Cireundeu, Ciputat Timur, Tangerang Selatan 15419',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah sumatera utara' => [
        'kode' => '011009',
        'singkat' => 'UMSU',
        'akred' => 'Unggul',
        'prov' => 'Sumatera Utara',
        'kab' => 'Kota Medan',
        'lat' => 3.608900,
        'lng' => 98.695600,
        'web' => 'https://umsu.ac.id',
        'alamat' => 'Jl. Kapten Mukhtar Basri No. 3, Glugur Darat II, Medan Timur, Medan 20238',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah riau' => [
        'kode' => '101021',
        'singkat' => 'UMRI',
        'akred' => 'Baik Sekali',
        'prov' => 'Riau',
        'kab' => 'Kota Pekanbaru',
        'lat' => 0.505600,
        'lng' => 101.425600,
        'web' => 'https://umri.ac.id',
        'alamat' => 'Jl. Tuanku Tambusai, Delima, Tampan, Pekanbaru, Riau 28292',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah makassar' => [
        'kode' => '091004',
        'singkat' => 'UNISMUH Makassar',
        'akred' => 'Unggul',
        'prov' => 'Sulawesi Selatan',
        'kab' => 'Kota Makassar',
        'lat' => -5.178900,
        'lng' => 119.435600,
        'web' => 'https://unismuh.ac.id',
        'alamat' => 'Jl. Sultan Alauddin No. 259, Gunung Sari, Rappocini, Makassar, Sulsel 90221',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah palembang' => [
        'kode' => '021008',
        'singkat' => 'UM Palembang',
        'akred' => 'Baik Sekali',
        'prov' => 'Sumatera Selatan',
        'kab' => 'Kota Palembang',
        'lat' => -2.995600,
        'lng' => 104.775600,
        'web' => 'https://um-palembang.ac.id',
        'alamat' => 'Jl. Jenderal Ahmad Yani 13 Ulu, Seberang Ulu II, Palembang, Sumsel 30263',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah bengkulu' => [
        'kode' => '021013',
        'singkat' => 'UMB',
        'akred' => 'Baik Sekali',
        'prov' => 'Bengkulu',
        'kab' => 'Kota Bengkulu',
        'lat' => -3.795600,
        'lng' => 102.285600,
        'web' => 'https://umb.ac.id',
        'alamat' => 'Jl. Bali, Teluk Segara, Kota Bengkulu 38119',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah pontianak' => [
        'kode' => '111007',
        'singkat' => 'UM Pontianak',
        'akred' => 'Baik Sekali',
        'prov' => 'Kalimantan Barat',
        'kab' => 'Kota Pontianak',
        'lat' => -0.045600,
        'lng' => 109.345600,
        'web' => 'https://unmuhpnk.ac.id',
        'alamat' => 'Jl. Jenderal Ahmad Yani No. 111, Bangka Belitung Laut, Pontianak Tenggara 78124',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah banjarmasin' => [
        'kode' => '111019',
        'singkat' => 'UM BJM',
        'akred' => 'Baik Sekali',
        'prov' => 'Kalimantan Selatan',
        'kab' => 'Kabupaten Barito Kuala',
        'lat' => -3.275600,
        'lng' => 114.585600,
        'web' => 'https://umbjm.ac.id',
        'alamat' => 'Jl. Gubernur Syarkawi, Lingkar Utara, Alalak, Barito Kuala, Kalsel 70114',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah kalimantan timur' => [
        'kode' => '111020',
        'singkat' => 'UMKT',
        'akred' => 'Baik Sekali',
        'prov' => 'Kalimantan Timur',
        'kab' => 'Kota Samarinda',
        'lat' => -0.465600,
        'lng' => 117.155600,
        'web' => 'https://umkt.ac.id',
        'alamat' => 'Jl. Ir. H. Juanda No. 15, Sidodadi, Samarinda Ulu, Samarinda, Kaltim 75124',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah kendari' => [
        'kode' => '091037',
        'singkat' => 'UM Kendari',
        'akred' => 'Baik Sekali',
        'prov' => 'Sulawesi Tenggara',
        'kab' => 'Kota Kendari',
        'lat' => -3.985600,
        'lng' => 122.525600,
        'web' => 'https://umkendari.ac.id',
        'alamat' => 'Jl. KH. Ahmad Dahlan No. 10, Wowawanggu, Kadia, Kendari, Sultra 93127',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah mataram' => [
        'kode' => '081011',
        'singkat' => 'UMMAT',
        'akred' => 'Baik Sekali',
        'prov' => 'Nusa Tenggara Barat',
        'kab' => 'Kota Mataram',
        'lat' => -8.575600,
        'lng' => 116.105600,
        'web' => 'https://ummat.ac.id',
        'alamat' => 'Jl. KH. Ahmad Dahlan No. 1, Pagesangan, Mataram, NTB 83127',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah kupang' => [
        'kode' => '081014',
        'singkat' => 'UMK',
        'akred' => 'Baik Sekali',
        'prov' => 'Nusa Tenggara Timur',
        'kab' => 'Kota Kupang',
        'lat' => -10.165600,
        'lng' => 123.625600,
        'web' => 'https://unmuhkupang.ac.id',
        'alamat' => 'Jl. K. H. Ahmad Dahlan No. 17, Kayu Putih, Oebobo, Kota Kupang, NTT 85111',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah sorong' => [
        'kode' => '141011',
        'singkat' => 'UNAMIN',
        'akred' => 'Baik Sekali',
        'prov' => 'Papua Barat Daya',
        'kab' => 'Kota Sorong',
        'lat' => -0.885600,
        'lng' => 131.285600,
        'web' => 'https://um-sorong.ac.id',
        'alamat' => 'Jl. Pendidikan No. 27, Remu Utara, Kota Sorong, Papua Barat Daya 98416',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas muhammadiyah papua' => [
        'kode' => '141013',
        'singkat' => 'UM Papua',
        'akred' => 'Baik',
        'prov' => 'Papua',
        'kab' => 'Kota Jayapura',
        'lat' => -2.585600,
        'lng' => 140.675600,
        'web' => 'https://umpapua.ac.id',
        'alamat' => 'Jl. Abepura - Kotaraja, Abepura, Kota Jayapura, Papua 99351',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],

    // --- PTS TERNAMA LAINNYA ---
    'universitas bina sarana informatika' => [
        'kode' => '031062',
        'singkat' => 'UBSI',
        'akred' => 'Baik Sekali',
        'prov' => 'DKI Jakarta',
        'kab' => 'Kota Jakarta Pusat',
        'lat' => -6.185600,
        'lng' => 106.845600,
        'web' => 'https://bsi.ac.id',
        'alamat' => 'Jl. Kramat Raya No. 98, Senen, Jakarta Pusat 10450',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas mercu buana' => [
        'kode' => '031024',
        'singkat' => 'UMB',
        'akred' => 'Unggul',
        'prov' => 'DKI Jakarta',
        'kab' => 'Kota Jakarta Barat',
        'lat' => -6.208900,
        'lng' => 106.735600,
        'web' => 'https://mercubuana.ac.id',
        'alamat' => 'Jl. Meruya Selatan No. 1, Kembangan, Jakarta Barat 11650',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas gunadarma' => [
        'kode' => '031015',
        'singkat' => 'UG',
        'akred' => 'Unggul',
        'prov' => 'Jawa Barat',
        'kab' => 'Kota Depok',
        'lat' => -6.368900,
        'lng' => 106.835600,
        'web' => 'https://gunadarma.ac.id',
        'alamat' => 'Jl. Margonda Raya No. 100, Pondok Cina, Beji, Depok 16424',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas pelita harapan' => [
        'kode' => '041031',
        'singkat' => 'UPH',
        'akred' => 'Unggul',
        'prov' => 'Banten',
        'kab' => 'Kabupaten Tangerang',
        'lat' => -6.225600,
        'lng' => 106.605600,
        'web' => 'https://uph.edu',
        'alamat' => 'Jl. M. H. Thamrin Boulevard 1100, Lippo Karawaci, Tangerang 15811',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas multimedia nusantara' => [
        'kode' => '041058',
        'singkat' => 'UMN',
        'akred' => 'Unggul',
        'prov' => 'Banten',
        'kab' => 'Kabupaten Tangerang',
        'lat' => -6.255600,
        'lng' => 106.615600,
        'web' => 'https://umn.ac.id',
        'alamat' => 'Jl. Scientia Boulevard, Gading Serpong, Tangerang, Banten 15811',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas dian nuswantoro' => [
        'kode' => '061027',
        'singkat' => 'UDINUS',
        'akred' => 'Unggul',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kota Semarang',
        'lat' => -6.985600,
        'lng' => 110.405600,
        'web' => 'https://dinus.ac.id',
        'alamat' => 'Jl. Imam Bonjol No. 207, Pendrikan Kidul, Semarang Tengah, Kota Semarang 50131',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas kristen satya wacana' => [
        'kode' => '061002',
        'singkat' => 'UKSW',
        'akred' => 'Unggul',
        'prov' => 'Jawa Tengah',
        'kab' => 'Kota Salatiga',
        'lat' => -7.325600,
        'lng' => 110.505600,
        'web' => 'https://uksw.edu',
        'alamat' => 'Jl. Diponegoro No. 52-60, Sidorejo, Kota Salatiga, Jawa Tengah 50711',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
    'universitas sanata dharma' => [
        'kode' => '051008',
        'singkat' => 'USD',
        'akred' => 'Unggul',
        'prov' => 'DI Yogyakarta',
        'kab' => 'Kabupaten Sleman',
        'lat' => -7.775600,
        'lng' => 110.388900,
        'web' => 'https://usd.ac.id',
        'alamat' => 'Jl. Affandi, Caturtunggal, Depok, Sleman, DI Yogyakarta 55281',
        'jenis' => 'universitas',
        'kelompok' => 'PTS',
    ],
];

// Load existing raw data or master
$masterFile = __DIR__ . '/database/data/master_kampus_indonesia.json';
$existingMaster = file_exists($masterFile) ? json_decode(file_get_contents($masterFile), true) : [];

$mergedList = [];
$seen = [];

// 1. Prioritize curated additions
foreach ($curatedAdditions as $name => $c) {
    $cleanName = ucwords(strtolower($name));
    $norm = strtolower($cleanName);
    $seen[$norm] = true;

    $mergedList[] = [
        'id' => 'pt-' . $c['kode'],
        'nama_universitas' => $cleanName,
        'nama_singkat' => $c['singkat'] ?? null,
        'kode_univ' => $c['kode'],
        'jenis' => $c['jenis'] ?? 'universitas',
        'kelompok' => $c['kelompok'] ?? 'PTS',
        'akreditasi' => $c['akred'] ?? 'Unggul',
        'provinsi' => $c['prov'],
        'kabupaten_kota' => $c['kab'],
        'alamat_kampus' => $c['alamat'],
        'website' => $c['web'],
        'latitude' => $c['lat'],
        'longitude' => $c['lng'],
    ];
}

// 2. Append all other existing master universities
foreach ($existingMaster as $item) {
    $norm = strtolower(trim($item['nama_universitas']));
    if (!isset($seen[$norm])) {
        $seen[$norm] = true;
        $mergedList[] = $item;
    }
}

echo "Total updated master campuses: " . count($mergedList) . "\n";

// Save to backend data directory
file_put_contents($masterFile, json_encode($mergedList, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

// Save to frontend public/data directory
$frontendDir = dirname(__DIR__, 2) . '/Frontend/baktinusantara-frontend/public/data';
if (!is_dir($frontendDir)) {
    mkdir($frontendDir, 0777, true);
}
file_put_contents($frontendDir . '/master_kampus_indonesia.json', json_encode($mergedList, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

echo "Successfully synchronized to backend and frontend!\n";

// Test search for UMSIDA
$found = array_filter($mergedList, function($u) {
    return str_contains(strtolower($u['nama_universitas']), 'sidoarjo') || str_contains(strtolower($u['nama_singkat'] ?? ''), 'umsida');
});
echo "Found in Sidoarjo: " . count($found) . "\n";
foreach ($found as $u) {
    echo "-> " . $u['nama_universitas'] . " (Kode: " . $u['kode_univ'] . ", " . $u['akreditasi'] . ")\n";
}
